#####################
# ENVIREM VARIABLES #
#####################

# Load libraries
library(sf) # <- GIS
library(rgdal) # <- GIS
library(raster) # <- GIS
library(envirem) # <- To create climatic variables


#####################
# Connection to OSF #
#####################

main.path <- "YOUR_PATH"
setwd(main.path)


# Climate variables PRESENT-----------------------------------------------------
# Check temperatures degrees
tmax <- raster("./Present/tMax_crop/wc2.1_5m_tmax_01.tif")
tmin <- raster("./Present/tMin_crop/wc2.1_5m_tmin_01.tif")
tmax$wc2.1_5m_tmax_01@data # <- OK
tmin$wc2.1_5m_tmin_01@data # <- OK


#---------------------------------------------------------------#
# Preparation of climate variables to create environmental ones #
#---------------------------------------------------------------#

# Create folder containing all climate variables
dir.create("./Present/tMax_tMin_Prec")

# Move climate variable to tMax_tMin_Prec folder -------------------------------
# tMin
moveFrom <- list.files(path = "./Present/tMin_crop/", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("tMin_crop", "tMax_tMin_Prec", moveFrom)

file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./Present/tMin_crop/")

# tMax
moveFrom <- list.files(path = "./Present/tMax_crop", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("tMax_crop", "tMax_tMin_Prec", moveFrom)

file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./Present/tMax_crop/")

# Prec
moveFrom <- list.files(path = "./Present/Prec_crop", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("Prec_crop", "tMax_tMin_Prec", moveFrom)

file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./Present/Prec_crop/")


# Check the variables names ----------------------------------------------------
verifyFileStructure("./Present/tMax_tMin_Prec/", returnFileNames = FALSE)

# Select month numbers
assignNames(tmax = "wc2.1_5m_tmax_##",
            tmin = "wc2.1_5m_tmin_##",
            precip = "wc2.1_5m_prec_##")
verifyFileStructure("./Present/tMax_tMin_Prec/", returnFileNames = FALSE)

# Previously, extraterrestrial solar radiation needed to be acquired elsewhere, 
# but these can now be generated by the envirem R package, 
# thanks to the palinsol R package.
# 
# To generate monthly extraterrestrial solar radiation, we need to provide:
# a climatic raster, which will be used to match the raster grid,
# a year, which will be used to determine the angle of the sun,
# an output directory where the rasters will be written. The names of the output 
# rasters will be defined by the naming scheme defined previously.
# In the palinsol R package, year = 0 corresponds to the year 1950. 
# Therefore, as this is a climate projection for the years 2041-2060, 
# we can define the year as 2050 - 1950 = 100.

# Present scenario: 2000 - 1950 = 50
# Read in a climatic raster to use as a template to estimate solar radiation
rasterTemplate <- raster("./Present/tMax_tMin_Prec/wc2.1_5m_prec_01.tif")

# Calculate monthly solar radiation, defined for the year 2000. 
ETsolradRasters(rasterTemplate = rasterTemplate, year = 50, 
                outputDir = "./Present/tMax_tMin_Prec/", 
                overwrite = FALSE)

# Check variable names also with solar radiation
verifyFileStructure("./Present/tMax_tMin_Prec/", returnFileNames = FALSE)


# Clean workspace
rm(list=setdiff(ls(), c("main.path")))

# Load rasters to create environmental variables
# List of climate raster
climFiles <- list.files(path = "./Present/tMax_tMin_Prec/",
                        pattern ='.tif$', all.files = TRUE, full.names = TRUE)
climFiles <- climFiles[!grepl("solrad", climFiles)]

# List of solar radiation rasters
solarFiles <- list.files(path = "./Present/tMax_tMin_Prec/", 
                         pattern = 'solrad', all.files = TRUE, full.names = TRUE)

# Create raster stack with climatic and solar radiation rasters
climStack <- stack(climFiles)
solarStack <- stack(solarFiles)

par(mfrow=c(1, 2))
plot(climStack[[1]])
plot(solarStack[[1]])
dev.off()

# Check extention
extent(climStack) == extent(solarStack)
# Check resolution
xres(climStack) == xres(solarStack)

# Remove unnecessary objects
rm(climFiles, solarFiles)

# Check names
verifyRasterNames(climStack, solradstack = solarStack)

# Envirem variables creation
envirem.var <- layerCreation(climStack, solarStack, var = 'all')


# Create folder to save the raster
dir.create("./Present/envirem_crop")

# Save rasters
for(i in 1:length(names(envirem.var))){
  writeRaster(envirem.var [[i]], filename = paste0("./Present/envirem_crop/", 
              names(envirem.var)[i], ".tif"), 
              format = "GTiff", overwrite = FALSE)}; rm(i)


#----------------#
# MIROC-ESM-CHEM #
#----------------#

# FUTURE 2050 ------------------------------------------------------------------
tmax <- raster("./MIROC_2050/tMax_crop/mi45tx50_01.tif")
tmin <- raster("./MIROC_2050/tMin_crop/mi45tn50_01.tif")

tmax$mi45tx50_01@data # <- OK
tmin$mi45tn50_01@data # <- OK

# Create folder containing all climate variables
dir.create("./MIROC_2050/tMax_tMin_Prec")

# Move climate variable to tMax_tMin_Prec folder -------------------------------
moveFrom <- list.files(path = "./MIROC_2050/tMin_crop/", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("tMin_crop", "tMax_tMin_Prec", moveFrom)
file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./MIROC_2050/tMin_crop/")

moveFrom <- list.files(path = "./MIROC_2050/tMax_crop/", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("tMax_crop", "tMax_tMin_Prec", moveFrom)
file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./MIROC_2050/tMax_crop/")

moveFrom <- list.files(path = "./MIROC_2050/Prec_crop", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("Prec_crop", "tMax_tMin_Prec", moveFrom)
file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./MIROC_2050/Prec_crop/")


# Check the variables names ----------------------------------------------------
verifyFileStructure("./MIROC_2050/tMax_tMin_Prec/", returnFileNames = FALSE)

# Select month numbers
assignNames(tmax = "mi45tx50_##",
            tmin = "mi45tn50_##",
            precip = "mi45pr50_##")
verifyFileStructure("./MIROC_2050//tMax_tMin_Prec/", returnFileNames = FALSE)

# Read in a climatic raster to use as a template to estimate solar radiation
rasterTemplate <- raster("./MIROC_2050/mi45pr50_01.tif")
# Calculate monthly solar radiation, defined for the year 2000. 
ETsolradRasters(rasterTemplate = rasterTemplate, year = 100, 
                outputDir = "./MIROC_2050/tMax_tMin_Prec/", 
                overwrite = F)

# Check variable names
verifyFileStructure("./MIROC_2050/tMax_tMin_Prec/", returnFileNames = FALSE)

# Clean workspace
rm(list=setdiff(ls(), c("main.path")))


# Load rasters to create environmental variables
# List of climate raster
climFiles <- list.files(path = "./MIROC_2050/tMax_tMin_Prec/",
                        pattern ='.tif$', all.files = TRUE, full.names = TRUE)
climFiles <- climFiles[!grepl("solrad", climFiles)]
solarFiles <- list.files(path = "./MIROC_2050//tMax_tMin_Prec/", 
                         pattern = 'solrad', all.files = TRUE, full.names = TRUE)

climStack <- stack(climFiles)
solarStack <- stack(solarFiles)
rm(climFiles, solarFiles)

# Check extention
extent(climStack) == extent(solarStack)
# Check resolution
xres(climStack) == xres(solarStack)

# Check names again
verifyRasterNames(climStack, solradstack = solarStack)

# Creation of all envirem variables
envirem.var <- layerCreation(climStack, solarStack, var = 'all')

# Create folder to save the raster
dir.create("./MIROC_2050/envirem_crop")

# Save rasters
for(i in 1:length(names(envirem.var))){
  writeRaster(envirem.var [[i]], filename=paste0("./MIROC_2050/envirem_crop/", 
                                                 names(envirem.var)[i], ".tif"), 
              format="GTiff", overwrite=F)}; rm(i)

# FUTURE 2070 ------------------------------------------------------------------
tmax <- raster("./MIROC_2070/tMax_crop/mi45tx70_01.tif")
tmin <- raster("./MIROC_2070/mi45tn70/mi45tn70_01.tif")

tmax$mi45tx70_01@data # <- OK
tmin$mi45tn70_01@data # <- OK

# Create folder containing all climate variables
dir.create("./MIROC_2070/tMax_tMin_Prec")

# Move climate variable to tMax_tMin_Prec folder -------------------------------
moveFrom <- list.files(path = "./MIROC_2070/tMin_crop/", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("tMin_crop", "tMax_tMin_Prec", moveFrom)
file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./MIROC_2070/tMin_crop/")

moveFrom <- list.files(path = "./MIROC_2070/tMax_crop/", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("tMax_crop", "tMax_tMin_Prec", moveFrom)
file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./MIROC_2070/tMax_crop/")

moveFrom <- list.files(path = "./MIROC_2070/Prec_crop", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("Prec_crop", "tMax_tMin_Prec", moveFrom)
file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./MIROC_2070/Prec_crop/")


# Check the variables names ----------------------------------------------------
verifyFileStructure("./MIROC_2070/tMax_tMin_Prec/", returnFileNames = FALSE)

# Select month numbers
assignNames(tmax = "mi45tx70_##",
            tmin = "mi45tn70_##",
            precip = "mi45pr70_##")
verifyFileStructure("./MIROC_2070/tMax_tMin_Prec/", returnFileNames = FALSE)

# Read in a climatic raster to use as a template to estimate solar radiation
rasterTemplate <- raster("./MIROC_2070/mi45pr70_01.tif")
# Calculate monthly solar radiation, defined for the year 2000. 
ETsolradRasters(rasterTemplate = rasterTemplate, year = 120, 
                outputDir = "./MIROC_2070/tMax_tMin_Prec/", 
                overwrite = F)

# Check variable names
verifyFileStructure("./MIROC_2070/tMax_tMin_Prec/", returnFileNames = FALSE)


# Clean workspace
rm(list=setdiff(ls(), c("main.path")))


# Load rasters to create environmental variables
# List of climate raster
climFiles <- list.files(path = "./MIROC_2070/tMax_tMin_Prec/",
                        pattern ='.tif$', all.files = TRUE, full.names = TRUE)
climFiles <- climFiles[!grepl("solrad", climFiles)]
solarFiles <- list.files(path = "./MIROC_2070//tMax_tMin_Prec/", 
                         pattern = 'solrad', all.files = TRUE, full.names = TRUE)

climStack <- stack(climFiles)
solarStack <- stack(solarFiles)
rm(climFiles, solarFiles)

# Check extention
extent(climStack) == extent(solarStack)
# Check resolution
xres(climStack) == xres(solarStack)

# Check names again
verifyRasterNames(climStack, solradstack = solarStack)

# Creation of all envimer variables
envirem.var <- layerCreation(climStack, solarStack, var = 'all')

# Create folder to save the raster
dir.create("./MIROC_2070/envirem_crop")

# Save rasters
for(i in 1:length(names(envirem.var))){
  writeRaster(envirem.var [[i]], filename=paste0("./MIROC_2070/envirem_crop/", 
                                                 names(envirem.var)[i], ".tif"), 
              format="GTiff", overwrite=F)}; rm(i)


#-----------#
# NorESM1-M #
#-----------#

# FUTURE 2050 ------------------------------------------------------------------
tmax <- raster("./NOR_2050/tMax_crop/no45tx50_01.tif")
tmin <- raster("./NOR_2050/tMin_crop/no45tn50_01.tif")

tmax$no45tx50_01@data # <- OK
tmin$no45tn50_01@data # <- OK

# Create folder containing all climate variables
dir.create("./NOR_2050/tMax_tMin_Prec")

# Move climate variable to tMax_tMin_Prec folder -------------------------------
moveFrom <- list.files(path = "./NOR_2050/tMin_crop/", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("tMin_crop", "tMax_tMin_Prec", moveFrom)
file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./NORC_2050/tMin_crop/")

moveFrom <- list.files(path = "./NOR_2050/tMax_crop/", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("tMax_crop", "tMax_tMin_Prec", moveFrom)
file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./NOR_2050/tMax_crop/")

moveFrom <- list.files(path = "./NOR_2050/Prec_crop", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("Prec_crop", "tMax_tMin_Prec", moveFrom)
file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./NOR_2050/Prec_crop/")

# Check the variables names ----------------------------------------------------
verifyFileStructure("./NOR_2050/tMax_tMin_Prec/", returnFileNames = FALSE)

# Select month numbers
assignNames(tmax = "no45tx50_##",
            tmin = "no45tn50_##",
            precip = "no45pr50_##")
verifyFileStructure("./NOR_2050/tMax_tMin_Prec/", returnFileNames = FALSE)


# Read in a climatic raster to use as a template to estimate solar radiation
rasterTemplate <- raster("./NOR_2050/no45pr50_01.tif")
# Calculate monthly solar radiation, defined for the year 2000. 
ETsolradRasters(rasterTemplate = rasterTemplate, year = 100, 
                outputDir = "./no_2050/tMax_tMin_Prec/", 
                overwrite = F)

# Check variable names
verifyFileStructure("./no_2050/tMax_tMin_Prec/", returnFileNames = FALSE)

# Clean workspace
rm(list=setdiff(ls(), c("main.path")))

# Load rasters to create environmental variables
# List of climate raster
climFiles <- list.files(path = "./NOR_2050/tMax_tMin_Prec/",
                        pattern ='.tif$', all.files = TRUE, full.names = TRUE)
climFiles <- climFiles[!grepl("solrad", climFiles)]
solarFiles <- list.files(path = "./NOR_2050//tMax_tMin_Prec/", 
                         pattern = 'solrad', all.files = TRUE, full.names = TRUE)

climStack <- stack(climFiles)
solarStack <- stack(solarFiles)
rm(climFiles, solarFiles)

# Check extention
extent(climStack) == extent(solarStack)
# Check resolution
xres(climStack) == xres(solarStack)

# Check names again
verifyRasterNames(climStack, solradstack = solarStack)

# Creation of all envimer variables
envirem.var <- layerCreation(climStack, solarStack, var = 'all')

# Create folder to save the raster
dir.create("./NOR_2050/envirem_crop")

# Save rasters
for(i in 1:length(names(envirem.var))){
  writeRaster(envirem.var [[i]], filename=paste0("./NOR_2050/envirem_crop/", 
                                                 names(envirem.var)[i], ".tif"), 
              format="GTiff", overwrite=F)}; rm(i)

# FUTURE 2070 ------------------------------------------------------------------
tmax <- raster("./NOR_2070/tMax_crop/no45tx70_01.tif")
tmin <- raster("./NOR_2070/tMin_crop/no45tn70_01.tif")

tmax$no45tx70_01@data # <- OK
tmin$no45tn70_01@data # <- OK

# Create folder containing all climate variables
dir.create("./NOR_2070/tMax_tMin_Prec")

# Move climate variable to tMax_tMin_Prec folder -------------------------------
moveFrom <- list.files(path = "./NOR_2070/tMin_crop/", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("tMin_crop", "tMax_tMin_Prec", moveFrom)
file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./NOR_2070/tMin_crop/")

moveFrom <- list.files(path = "./NOR_2070/tMax_crop/", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("tMax_crop", "tMax_tMin_Prec", moveFrom)
file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./NOR_2070/tMax_crop/")

moveFrom <- list.files(path = "./NOR_2070/Prec_crop", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("Prec_crop", "tMax_tMin_Prec", moveFrom)
file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./NOR_2070/Prec_crop/")

# Check the variables names ----------------------------------------------------
verifyFileStructure("./NOR_2050/tMax_tMin_Prec/", returnFileNames = FALSE)

# Change the names...
assignNames(tmax = "no45tx70_##",
            tmin = "no45tn70_##",
            precip = "no45pr70_##")
verifyFileStructure("./NOR_2050//tMax_tMin_Prec/", returnFileNames = FALSE)

# Read in a climatic raster to use as a template to estimate solar radiation
rasterTemplate <- raster("./NOR_2070/no45pr70_01.tif")
# Calculate monthly solar radiation, defined for the year 2000. 
ETsolradRasters(rasterTemplate = rasterTemplate, year = 120, 
                outputDir = "./NOR_2070/tMax_tMin_Prec/", 
                overwrite = F)

# Check variable names
verifyFileStructure("./MIROC_2050/tMax_tMin_Prec/", returnFileNames = FALSE)

# Clean workspace
rm(list=setdiff(ls(), c("main.path")))

# Load rasters to create environmental variables
# List of climate raster
climFiles <- list.files(path = "./NOR_2070/tMax_tMin_Prec/",
                        pattern ='.tif$', all.files = TRUE, full.names = TRUE)
climFiles <- climFiles[!grepl("solrad", climFiles)]
solarFiles <- list.files(path = "./NOR_2070/tMax_tMin_Prec/", 
                         pattern = 'solrad', all.files = TRUE, full.names = TRUE)

climStack <- stack(climFiles)
solarStack <- stack(solarFiles)
rm(climFiles, solarFiles)

# Check extention
extent(climStack) == extent(solarStack)
# Check resolution
xres(climStack) == xres(solarStack)

# Check names again
verifyRasterNames(climStack, solradstack = solarStack)

# Creation of all envimer variables
envirem.var <- layerCreation(climStack, solarStack, var = 'all')

# Create folder to save the raster
dir.create("./NOR_2070/envirem_crop")

# Save rasters
for(i in 1:length(names(envirem.var))){
  writeRaster(envirem.var [[i]], filename=paste0("./NOR_2070/envirem_crop/", 
                                                 names(envirem.var)[i], ".tif"), 
              format="GTiff", overwrite=F)}; rm(i)

#------------#
# BCC-CSM1-1 #
#------------#

# FUTURE 2050 ------------------------------------------------------------------
tmax <- raster("./BCC_2050/tMax_crop/bc45tx50_01.tif")
tmin <- raster("./BCC_2050/tMin_crop/bc45tn50_01.tif")

tmax$bc45tx50_01@data # <- OK
tmin$bc45tn50_01@data # <- OK

# Create folder containing all climate variables
dir.create("./BCC_2050/tMax_tMin_Prec")

# Move climate variable to tMax_tMin_Prec folder -------------------------------
moveFrom <- list.files(path = "./BCC_2050/tMin_crop/", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("tMin_crop", "tMax_tMin_Prec", moveFrom)
file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./BCC_2050/tMin_crop/")

moveFrom <- list.files(path = "./BCC_2050/tMax_crop/", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("tMax_crop", "tMax_tMin_Prec", moveFrom)
file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./BCC_2050/tMax_crop/")

moveFrom <- list.files(path = "./BCC_2050/Prec_crop", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("Prec_crop", "tMax_tMin_Prec", moveFrom)
file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./BCC_2050/Prec_crop/")

# Check the variables names ----------------------------------------------------
verifyFileStructure("./BCC_2050/tMax_tMin_Prec/", returnFileNames = FALSE)

# Change the names...
assignNames(tmax = "bc45tx50_##",
            tmin = "bc45tn50_##",
            precip = "bc45pr50_##")
verifyFileStructure("./BCC_2050//tMax_tMin_Prec/", returnFileNames = FALSE)

# Read in a climatic raster to use as a template to estimate solar radiation
rasterTemplate <- raster("./BCC_2050/bc45pr50_01.tif")
# Calculate monthly solar radiation, defined for the year 2000. 
ETsolradRasters(rasterTemplate = rasterTemplate, year = 100, 
                outputDir = "./BCC_2050/tMax_tMin_Prec/", 
                overwrite = F)

# Check variable names
verifyFileStructure("./BCC_2050/tMax_tMin_Prec/", returnFileNames = FALSE)

# Clean workspace
rm(list=setdiff(ls(), c("main.path")))

# Load rasters to create environmental variables
# List of climate raster
climFiles <- list.files(path = "./BCC_2050/tMax_tMin_Prec/",
                        pattern ='.tif$', all.files = TRUE, full.names = TRUE)
climFiles <- climFiles[!grepl("solrad", climFiles)]
solarFiles <- list.files(path = "./BCC_2050//tMax_tMin_Prec/", 
                         pattern = 'solrad', all.files = TRUE, full.names = TRUE)

climStack <- stack(climFiles)
solarStack <- stack(solarFiles)
rm(climFiles, solarFiles)

# Check extention
extent(climStack) == extent(solarStack)
# Check resolution
xres(climStack) == xres(solarStack)

# Check names again
verifyRasterNames(climStack, solradstack = solarStack)

# Creation of all envimer variables
envirem.var <- layerCreation(climStack, solarStack, var = 'all')

# Create folder to save the raster
dir.create("./BCC_2050//envirem_crop")

# Save rasters
for(i in 1:length(names(envirem.var))){
  writeRaster(envirem.var [[i]], filename=paste0("./BCC_2050/envirem_crop/", 
                                                 names(envirem.var)[i], ".tif"), 
              format="GTiff", overwrite=F)}; rm(i)

# FUTURE 2070 ------------------------------------------------------------------
tmax <- raster("./BCC_2050/tMax_crop/bc45tx70_01.tif")
tmin <- raster("./BCC_2050/tMin_crop/bc45tn70_01.tif")

tmax$bc45tx70_01@data # <- OK
tmin$bc45tn70_01@data # <- OK

# Create folder containing all climate variables
dir.create("./BCC_2070/tMax_tMin_Prec")

# Move climate variable to tMax_tMin_Prec folder -------------------------------
moveFrom <- list.files(path = "./BCC_2070/tMin_crop/", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("tMin_crop", "tMax_tMin_Prec", moveFrom)
file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./BCC_2070/tMin_crop/")

moveFrom <- list.files(path = "./BCC_2070/tMax_crop/", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("tMax_crop", "tMax_tMin_Prec", moveFrom)
file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./BCC_2070/tMax_crop/")

moveFrom <- list.files(path = "./BCC_2070/Prec_crop", pattern = '.tif$', 
                       all.files = TRUE, full.names = TRUE)
moveTo <- gsub("Prec_crop", "tMax_tMin_Prec", moveFrom)
file.copy(from = moveFrom, to = moveTo ) 
rm(moveFrom); file.remove("./BCC_2070/Prec_crop/")

# Check the variables names ----------------------------------------------------
verifyFileStructure("./BCC_2070/tMax_tMin_Prec/", returnFileNames = FALSE)

# Change the names...
assignNames(tmax = "bc45tx70_##",
            tmin = "bc45tn70_##",
            precip = "bc45pr70_##")
verifyFileStructure("./BCC_2070/tMax_tMin_Prec/", returnFileNames = FALSE)

# Read in a climatic raster to use as a template to estimate solar radiation
rasterTemplate <- raster("./BCC_2050/bc45pr70_01.tif")
# Calculate monthly solar radiation, defined for the year 2000. 
ETsolradRasters(rasterTemplate = rasterTemplate, year = 120, 
                outputDir = "./BCC_2050/tMax_tMin_Prec/", 
                overwrite = F)

# Check variable names
verifyFileStructure("./BCC_2070/tMax_tMin_Prec/", returnFileNames = FALSE)

# Clean workspace
rm(list=setdiff(ls(), c("main.path")))


# Load rasters to create environmental variables
# List of climate raster
climFiles <- list.files(path = "./BCC_2070/tMax_tMin_Prec/",
                        pattern ='.tif$', all.files = TRUE, full.names = TRUE)
climFiles <- climFiles[!grepl("solrad", climFiles)]
solarFiles <- list.files(path = "./BCC_2070/tMax_tMin_Prec/", 
                         pattern = 'solrad', all.files = TRUE, full.names = TRUE)

climStack <- stack(climFiles)
solarStack <- stack(solarFiles)
rm(climFiles, solarFiles)

# Check extention
extent(climStack) == extent(solarStack)
# Check resolution
xres(climStack) == xres(solarStack)

# Check names again
verifyRasterNames(climStack, solradstack = solarStack)

# Creation of all envimer variables
envirem.var <- layerCreation(climStack, solarStack, var = 'all')

# Create folder to save the raster
dir.create("./BCC_2070/envirem_crop")

# Save rasters
for(i in 1:length(names(envirem.var))){
  writeRaster(envirem.var [[i]], filename=paste0("./BCC_2070/envirem_crop/", 
                                                 names(envirem.var)[i], ".tif"), 
              format="GTiff", overwrite=F)}; rm(i)
